version: "3.5"

x-logging:
 &logging-config
  driver: json-file
  options:
   max-size: "200k"
   max-file: "10"
x-healthcheck:
 &healthcheck-config
  test: ["CMD", "curl", "-f", "http://localhost"]
  interval: 1m30s
  timeout: 10s
  retries: 3

services:
  gui:
   image: agile_gui:latest
   restart: on-failure
   ports:
    - 3000:3000
   volumes:
    - "./config/configuration.json:/opt/agile/configuration.js:z"
   networks:
    - agile-network

  administrator:
    image: agile/administrator-service:latest
    restart: on-failure
    ports:
      - 9000:9000
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - agile-network

  central:
    image: agile/central-service:latest
    restart: on-failure
    ports:
      - 9005:9005
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - agile-network

  db:
   image: postgres:12
   ports:
    - 5432:5432
   restart: on-failure
   logging: *logging-config
   environment:
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=admin123
    - POSTGRES_DB=agile
   volumes:
    - agile_postgres_data:/var/lib/postgresql/data
   networks:
    - agile-network

  pg-admin:
   image: dpage/pgadmin4:latest
   logging: *logging-config
   restart: on-failure
   ports:
    - 5050:80
   links:
    - db
   environment:
    - PGADMIN_DEFAULT_EMAIL=markoperajicca@gmail.com
    - PGADMIN_DEFAULT_PASSWORD=admin123
    - PGADMIN_LISTEN_PORT=80
   volumes:
    - agile_pgadmin_data:/var/lib/pgadmin
  redis:
   image: redis
   logging: *logging-config
   restart: on-failure
   ports:
    - 6379:6379
   networks:
    - agile-network
   volumes:
     - agile_redis_data:/var/lib/redis
   environment:
     - REDIS_REPLICATION_MODE=master

  maildevserver:
    image: maildev/maildev
    ports:
     - 1080:80
     - 1025:25
    networks:
     - agile-network

volumes:
  agile_postgres_data:
  agile_pgadmin_data:
  agile_redis_data:

networks:
  agile-network:
