spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://db:5432/agile}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin123}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    #      default_schema: src/main/resources/create_table.sql
    #      format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect